gha: Skip non-relevant checks on pr or merge_group

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -4,19 +4,63 @@ on:
   workflow_dispatch:
   push:
     branches:
-      - "develop"
+      - develop
+      - releases/**
     tags:
       - "v*"
   pull_request:
+  merge_group:
+    branches:
+      - develop
+      - releases/**
+
+permissions: {} # No permissions by default on workflow level
 
 jobs:
+  # Determines if workflow should execute based on event type and changed paths
+  # If push or workflow_dispatch -> always run
+  # If PR or merge_group -> run only if files in specified paths changed
+  check_paths:
+    name: Check if workflow should run
+    runs-on: ubuntu-latest
+    outputs:
+      run_workflow: ${{ steps.run_workflow.outputs.run }}
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
+        with:
+          persist-credentials: false
+
+      - name: Get all paths that should trigger the workflow
+        id: changed-files-yaml
+        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46.0.5
+        with:
+          files_yaml: |
+            test:
+              - ui/**
+              - backend/**
+              - docker/**
+              - .github/**
+
+      - name: Set run flag
+        id: run_workflow
+        run: |
+          if [ "${{ github.event_name }}" = "push" ] || [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
+            echo "run=true" >> "$GITHUB_OUTPUT"
+          elif [ "${{ steps.changed-files-yaml.outputs.test_any_changed }}" = "true" ]; then
+            echo "run=true" >> "$GITHUB_OUTPUT"
+          else
+            echo "run=false" >> "$GITHUB_OUTPUT"
+          fi
+
   build:
     name: Build and upload docker image
     runs-on: ubuntu-latest
+    needs: check_paths
+    if: needs.check_paths.outputs.run_workflow == 'true'
     permissions:
       contents: read
       pull-requests: write
-
     steps:
       - name: Checkout repository
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
@@ -126,7 +170,9 @@ jobs:
 
       - name: Comment PR with image sizes
         uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
-        if: github.event_name == 'pull_request'
+        if: |
+          github.event_name == 'pull_request' &&
+          github.event.pull_request.head.repo.full_name == github.repository
         env:
           SIZES_CONTENT: ${{ steps.image-sizes.outputs.SIZES_CONTENT }}
         with:
@@ -169,3 +215,23 @@ jobs:
           path: |
             docker/geti-tune-*.tar
           retention-days: 7
+
+  required_check:
+    name: Required Check build
+    needs:
+      - check_paths
+      - build
+    runs-on: ubuntu-latest
+    env:
+      CHECKS: ${{ join(needs.*.result, ' ') }}
+    if: always() && !cancelled()
+    steps:
+      - name: Check jobs results
+        run: |
+          for check in ${CHECKS}; do
+            echo "::notice::check=${check}"
+            if [[ "$check" != "success" && "$check" != "skipped" ]]; then
+              echo "::error ::Required status checks failed. They must succeed before this pull request can be merged."
+              exit 1
+            fi
+          done
