gha: Skip non-relevant checks on pr or merge_group (#4684)

diff --git a/.github/workflows/ui-lint-and-test.yaml b/.github/workflows/ui-lint-and-test.yaml
--- a/.github/workflows/ui-lint-and-test.yaml
+++ b/.github/workflows/ui-lint-and-test.yaml
@@ -2,15 +2,40 @@ name: Geti Tune UI checks
 
 on:
   push:
-    branches: ["develop"]
+    branches:
+      - develop
+    tags:
+      - "v*"
   pull_request:
+  merge_group:
+    branches:
+      - develop
+      - releases/**
 
 permissions: {} # No permissions by default on workflow level
 
 jobs:
+  check_paths:
+    name: Check if workflow should run
+    runs-on: ubuntu-latest
+    outputs:
+      test_any_changed: ${{ steps.changed-files-yaml.outputs.test_any_changed }}
+    steps:
+      - name: Get all paths that should trigger the workflow
+        id: changed-files-yaml
+        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46.0.5
+        with:
+          files_yaml: |
+            test:
+              - backend/**
+              - ui/**
+              - .github/**
+
   generate-openapi-spec:
     name: Generate OpenAPI Spec
     runs-on: ubuntu-latest
+    needs: check_paths
+    if: needs.check_paths.outputs.test_any_changed == 'true'
     permissions:
       contents: read # to checkout code
     steps:
@@ -25,9 +50,10 @@ jobs:
           python-version: "3.13"
 
       - name: Install uv
-        uses: astral-sh/setup-uv@a02a550bdd3185dba2ebb6aa98d77047ce54ad21 # v6.2.1
+        uses: astral-sh/setup-uv@557e51de59eb14aaaba2ed9621916900a91d50c6 # v6.6.1
         with:
           version: "0.8.8"
+          enable-cache: false
 
       - name: Install OpenCV dependencies
         run: |
@@ -54,6 +80,8 @@ jobs:
   build:
     name: Build UI
     runs-on: ubuntu-latest
+    needs: check_paths
+    if: needs.check_paths.outputs.test_any_changed == 'true'
     permissions:
       contents: read # to checkout code
     steps:
@@ -87,9 +115,12 @@ jobs:
   lint:
     name: Eslint checks
     runs-on: ubuntu-latest
+    needs:
+      - check_paths
+      - generate-openapi-spec
+    if: needs.check_paths.outputs.test_any_changed == 'true'
     permissions:
       contents: read # to checkout code
-    needs: generate-openapi-spec
     steps:
       - name: Checkout code
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
@@ -134,10 +165,13 @@ jobs:
   unit-tests:
     name: Unit tests
     runs-on: ubuntu-latest
+    needs:
+      - check_paths
+      - generate-openapi-spec
+    if: needs.check_paths.outputs.test_any_changed == 'true'
     permissions:
       contents: read
       pull-requests: write
-    needs: generate-openapi-spec
     steps:
       - name: Checkout code
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
@@ -237,8 +271,10 @@ jobs:
   playwright-tests:
     name: Playwright Tests
     needs:
+      - check_paths
       - build
       - generate-openapi-spec
+    if: needs.check_paths.outputs.test_any_changed == 'true'
     permissions:
       contents: read # to checkout code
     timeout-minutes: 60
@@ -291,3 +327,27 @@ jobs:
           name: playwright-report
           path: ui/playwright-report/
           retention-days: 30
+
+  required_check:
+    name: Required Check ui-lint-and-test
+    needs:
+      - check_paths
+      - generate-openapi-spec
+      - build
+      - lint
+      - unit-tests
+      - playwright-tests
+    runs-on: ubuntu-latest
+    env:
+      CHECKS: ${{ join(needs.*.result, ' ') }}
+    if: always() && !cancelled()
+    steps:
+      - name: Check jobs results
+        run: |
+          for check in ${CHECKS}; do
+            echo "::notice::check=${check}"
+            if [[ "$check" != "success" && "$check" != "skipped" ]]; then
+              echo "::error ::Required status checks failed. They must succeed before this pull request can be merged."
+              exit 1
+            fi
+          done
